### ISSUE TITLE
Console Error, searches for helpdb folder under the .package path.

### ISSUE THREAD

**Issue by nekoniaow** [Swoffa/SublimeKickAssemblerC64#75]
With the current version of KickAssemblerC64 and Sublime Build 4180,
KickAssemblerC64 generates an error in the console when Sublime initializes.

It looks like the `KickassTooltip.py` script tries to list the content of the `helpdb` folder, however it seems to generate that file's path by combining the path of the compiled/compressed package then asking the OS to list its content, which obviously cannot work.

Here is the callstack as present in the Sublime Console:
```
Traceback (most recent call last):
  File "/Users/****/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 528, in on_api_ready
    plc()
  File "/Users/****/Library/Application Support/Sublime Text 3/Installed Packages/Kick Assembler (C64).sublime-package/KickassTooltips.py", line 171, in plugin_loaded
    tooltip.load()
  File "/Users/****/Library/Application Support/Sublime Text 3/Installed Packages/Kick Assembler (C64).sublime-package/KickassTooltips.py", line 74, in load
    self._load_definition()
  File "/Users/****/Library/Application Support/Sublime Text 3/Installed Packages/Kick Assembler (C64).sublime-package/KickassTooltips.py", line 85, in _load_definition
    for fname in os.listdir(dirname):
FileNotFoundError: [Errno 2] No such file or directory: '/Users/****/Library/Application Support/Sublime Text 3/Packages/Kick Assembler (C64)/helpdb'
```

As you can see, it searches in `/Users/****/Library/Application Support/Sublime Text 3/Packages/Kick Assembler (C64)/helpdb` which isn't a file system path.

**Comment by nekoniaow** [comment]
I forgot to mention that this is on macOS (obviously).
